stages:
  - stage: Build
    displayName: Build and Push Container Image
    jobs:
      - job: build_and_push_container_image
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: DockerCompose@0
            displayName: "Build Image"
            inputs:
              azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
              azureContainerRegistry: $(azureContainerRegistry)
              dockerComposeFile: "**/docker-compose.yml"
              action: "Build services"
              # The following parameter allows you to add additional tags to the image
              additionalImageTags: "$(Build.BuildId)"
              includeLatestTag: true
          - task: DockerCompose@0
            displayName: "Push Images"
            inputs:
              containerregistrytype: "Azure Container Registry"
              azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
              azureContainerRegistry: $(azureContainerRegistry)
              dockerComposeFile: "**/docker-compose.yml"
              action: "Push services"
              # The following parameter allows you to add additional tags to the image
              additionalImageTags: "$(Build.BuildId)"
              includeLatestTag: true
