version: '3.8'

services:
  nginx-hello:
    image: nginx-hello
    container_name: nginx-hello
    build:
      context: .
      dockerfile: ./Dockerfile
    expose:
      - 80
    ports:
      - 3030:80
    environment:
      - DOCKER_TAG
